import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '../styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      ({/* TODO: Eyða þessu, placeholder á forsíðu */})
      <div className={styles.main}>
        <h1>VELKOMIN Á MATARSÍÐUNA!!!!!!! :D</h1>
      </div>
    </>
  )
}
